/**
 * Content builder for base64.d.ts — the encoded map keyed by the exact name
 * union. Pure string producer, no filesystem writes. The value shape follows the
 * surface's `themes`: icons nest by theme (name → variant → theme → uri),
 * illustrations don't (name → variant → uri). Symbol name comes from `naming`.
 *
 * @module generateIndex/generateBase64Types
 */

/** Generate base64.d.ts — the encoded map keyed by the exact name union, nested
 * by theme for icons and flat (variant → uri) for illustrations. */
export function generateBase64Types(naming, themes) {
  const nameUnion = `(typeof import("./catalog").${naming.namesConst})[number]`

  if (themes) {
    return [
      `// GENERATED by generateIndex — do not edit by hand`,
      ``,
      `/** SVG base64 data-URIs for every icon, keyed by name → variant → theme`,
      ` * ("base" = #000, "night" = #fff). Color is baked in; consume directly as an`,
      ` * <img> src, CSS url(), or mask-image. Read via \`getIconEncoded\`. */`,
      `export const ${naming.base64Const}: Readonly<`,
      `  Record<`,
      `    ${nameUnion},`,
      `    Readonly<Record<string, Readonly<Record<string, string>>>>`,
      `  >`,
      `>;`,
      ``,
    ].join("\n")
  }

  return [
    `// GENERATED by generateIndex — do not edit by hand`,
    ``,
    `/** SVG base64 data-URIs for every illustration, keyed by name → variant → uri.`,
    ` * Colors are authored into the SVG (no theme dimension); consume directly as an`,
    ` * <img> src, CSS url(), or mask-image. Read via \`getIllustrationEncoded\`. */`,
    `export const ${naming.base64Const}: Readonly<`,
    `  Record<${nameUnion}, Readonly<Record<string, string>>>`,
    `>;`,
    ``,
  ].join("\n")
}
