/**
 * Content builder for source.d.ts — the source map keyed by the exact name
 * union, each an open map of variant stem → SVG string. Pure string producer,
 * no filesystem writes. Symbol name comes from the surface's `naming`.
 *
 * @module generateIndex/generateSourceTypes
 */

/** Generate source.d.ts — the source map keyed by the exact name union (from the
 * catalog tuple), each an open map of variant stem → SVG string. */
export function generateSourceTypes(naming) {
  return [
    `// GENERATED by generateIndex — do not edit by hand`,
    ``,
    `/** Raw, inline-ready SVG markup for every asset, keyed by name then variant`,
    ` * stem (base first). Framework-agnostic string source consumed by the getter. */`,
    `export const ${naming.sourceConst}: Readonly<`,
    `  Record<(typeof import("./catalog").${naming.namesConst})[number], Readonly<Record<string, string>>>`,
    `>;`,
    ``,
  ].join("\n")
}
