/**
 * Content builder for base64.d.ts — `iconBase64` keyed by the exact name union,
 * each an open map of variant stem → theme → data-URI string. Pure string
 * producer, no filesystem writes.
 *
 * @module generateIndex/generateBase64Types
 */

/** Generate base64.d.ts — `iconBase64` keyed by the exact name union, each an
 * open map of variant stem → theme → data-URI string. */
export function generateBase64Types() {
  return [
    `// GENERATED by generateIndex — do not edit by hand`,
    ``,
    `/** SVG base64 data-URIs for every icon, keyed by name → variant → theme`,
    ` * ("base" = #000, "night" = #fff). Color is baked in; consume directly as an`,
    ` * <img> src, CSS url(), or mask-image. Read via \`getIconEncoded\`. */`,
    `export const iconBase64: Readonly<`,
    `  Record<`,
    `    (typeof import("./catalog").iconNames)[number],`,
    `    Readonly<Record<string, Readonly<Record<string, string>>>>`,
    `  >`,
    `>;`,
    ``,
  ].join("\n")
}