/**
 * Content builder for source.d.ts — `iconSource` keyed by the exact name union,
 * each an open map of variant stem → SVG string. Pure string producer, no
 * filesystem writes.
 *
 * @module generateIndex/generateSourceTypes
 */

/** Generate source.d.ts — `iconSource` keyed by the exact name union (from the
 * catalog tuple), each an open map of variant stem → SVG string. */
export function generateSourceTypes() {
  return [
    `// GENERATED by generateIndex — do not edit by hand`,
    ``,
    `/** Raw, inline-ready SVG markup for every icon, keyed by name then variant`,
    ` * stem (base first). Framework-agnostic string source consumed by \`getIcon\`. */`,
    `export const iconSource: Readonly<`,
    `  Record<(typeof import("./catalog").iconNames)[number], Readonly<Record<string, string>>>`,
    `>;`,
    ``,
  ].join("\n")
}