/**
 * Content builders — turn the icon list into the text of each generated file
 * (index, catalog, source, and their .d.ts twins). Pure string producers with no
 * filesystem writes; ./write.js orchestrates reading the icons and writing these.
 *
 * @module generateIndex/generate
 */

import { toPascalCase, readIconSvg } from "./icons.js"

/**
 * Generate index.js content from the icon list. One export per variant:
 * base -> `${Name}BaseIcon`, fill -> `${Name}FillIcon`, 3d -> `${Name}3dIcon`.
 */
export function generateIndexContent(icons) {
  const lines = []

  for (const { name, variants } of icons) {
    const pascalName = toPascalCase(name)
    for (const variant of variants) {
      const exportName = `${pascalName}${toPascalCase(variant)}Icon`
      lines.push(`export { default as ${exportName} } from "./${name}/${variant}.svg";`)
    }
  }

  lines.push("")

  // Names + per-icon variants are data only (no SVG imports), so they live in the
  // ./catalog entry that tooling can import without dragging in every icon module.
  // Re-exported here for the default "nice-icons" entry.
  lines.push(`export { iconNames, iconVariants } from "./catalog.js";`)
  lines.push("")

  return lines.join("\n")
}

/**
 * Generate catalog.js — the data-only surface: `iconNames` (flat) and
 * `iconVariants` (per-icon variant lists, base first). No SVG imports, so
 * importing it (e.g. from the Storybook reference table) pulls no icon modules.
 */
export function generateCatalogContent(icons) {
  const lines = []

  lines.push("export const iconNames = [")
  for (const { name } of icons) {
    lines.push(`  "${name}",`)
  }
  lines.push("];")
  lines.push("")

  // Per-icon variant lists (base first), so a consumer can validate a requested
  // variant against what an icon actually ships — without importing SVG modules.
  lines.push("export const iconVariants = {")
  for (const { name, variants } of icons) {
    lines.push(`  "${name}": [${variants.map((v) => `"${v}"`).join(", ")}],`)
  }
  lines.push("};")
  lines.push("")

  return lines.join("\n")
}

/** Generate catalog.d.ts — `iconNames` as a readonly literal tuple (so the name
 * union stays exact) and `iconVariants` keyed by the exact name union. */
export function generateCatalogTypes(icons) {
  const lines = []

  lines.push("export const iconNames: readonly [")
  for (const { name } of icons) {
    lines.push(`  "${name}",`)
  }
  lines.push("];")
  lines.push("")

  lines.push(
    `export const iconVariants: Readonly<Record<(typeof iconNames)[number], readonly string[]>>;`
  )
  lines.push("")

  return lines.join("\n")
}

/**
 * Generate index.d.ts — the single typed surface consumers derive from. Every
 * icon export is an SvgComponent; `iconNames` is a readonly literal tuple so
 * downstream `(typeof iconNames)[number]` yields the exact name union (not a
 * widened `string`). Regenerated with index.js, so it can never drift.
 */
export function generateTypesContent(icons) {
  const lines = [
    `import * as React from "react";`,
    ``,
    `type SvgComponent = React.FunctionComponent<React.SVGAttributes<SVGElement>>;`,
    ``,
  ]

  for (const { name, variants } of icons) {
    const pascalName = toPascalCase(name)
    for (const variant of variants) {
      lines.push(`export const ${pascalName}${toPascalCase(variant)}Icon: SvgComponent;`)
    }
  }

  lines.push("")
  lines.push(`export { iconNames, iconVariants } from "./catalog";`)
  lines.push("")

  return lines.join("\n")
}

/**
 * Generate source.js — the raw, inline-ready SVG markup for every icon, keyed by
 * name then variant stem (`{ check: { base: "<svg…>", fill: "…" } }`). This is
 * the framework-agnostic string surface the vanilla `getIcon` reads from; it
 * holds only strings (no SVG module imports), so a non-bundler consumer can load
 * it directly. Serialized via JSON.stringify so markup is escaped correctly.
 */
export function generateSourceContent(icons) {
  const source = {}
  for (const { name, variants } of icons) {
    source[name] = {}
    for (const variant of variants) {
      source[name][variant] = readIconSvg(name, variant)
    }
  }
  return `// GENERATED by generateIndex — do not edit by hand\n\nexport const iconSource = ${JSON.stringify(
    source,
    null,
    2
  )};\n`
}

/** Generate source.d.ts — `iconSource` keyed by the exact name union (from the
 * catalog tuple), each an open map of variant stem → SVG string. */
export function generateSourceTypes() {
  return [
    `// GENERATED by generateIndex — do not edit by hand`,
    ``,
    `/** Raw, inline-ready SVG markup for every icon, keyed by name then variant`,
    ` * stem (base first). Framework-agnostic string source consumed by \`getIcon\`. */`,
    `export const iconSource: Readonly<`,
    `  Record<(typeof import("./catalog").iconNames)[number], Readonly<Record<string, string>>>`,
    `>;`,
    ``,
  ].join("\n")
}
