/**
 * Content builder for source.js — the raw, inline-ready SVG markup for every
 * asset, keyed by name then variant. The framework-agnostic string surface the
 * vanilla getters read from. Pure string producer, no filesystem writes. The
 * exported symbol name comes from the surface's `naming` (`iconSource` /
 * `illustrationSource`).
 *
 * @module generateIndex/generateSourceContent
 */

import { readIconSvg } from "./icons.js"

/**
 * Generate source.js — the raw, inline-ready SVG markup for every asset, keyed
 * by name then variant stem (`{ check: { base: "<svg…>", fill: "…" } }`). This
 * is the framework-agnostic string surface the vanilla getters read from; it
 * holds only strings (no SVG module imports), so a non-bundler consumer can load
 * it directly. Serialized via JSON.stringify so markup is escaped correctly.
 */
export function generateSourceContent(icons, generatedDir, naming) {
  const source = {}
  for (const { name, variants } of icons) {
    source[name] = {}
    for (const variant of variants) {
      source[name][variant] = readIconSvg(generatedDir, name, variant)
    }
  }
  return `// GENERATED by generateIndex — do not edit by hand\n\nexport const ${naming.sourceConst} = ${JSON.stringify(
    source,
    null,
    2
  )};\n`
}
