/**
 * Serialize the base64 map into the text of base64.js — the encoded counterpart
 * to source.js, consumed by the vanilla `getIconEncoded`. Strings only (no SVG
 * module imports), so a non-bundler consumer can load it directly.
 *
 * @module generateIndex/serializeBase64Module
 */

/** Serialize the base64 map to the base64.js module text (`export const iconBase64 = …`). */
export function serializeBase64Module(map) {
  return `// GENERATED by generateIndex — do not edit by hand\n\nexport const iconBase64 = ${JSON.stringify(
    map,
    null,
    2
  )};\n`
}