/**
 * Serialize the base64 map into the text of base64.js — the encoded counterpart
 * to source.js, consumed by the vanilla encoded getters. Strings only (no SVG
 * module imports), so a non-bundler consumer can load it directly. The exported
 * symbol name comes from the surface's `naming` (`iconBase64` /
 * `illustrationBase64`).
 *
 * @module generateIndex/serializeBase64Module
 */

/** Serialize the base64 map to the base64.js module text (`export const … = …`). */
export function serializeBase64Module(map, naming) {
  return `// GENERATED by generateIndex — do not edit by hand\n\nexport const ${naming.base64Const} = ${JSON.stringify(
    map,
    null,
    2
  )};\n`
}
